config/routes.rb
Rails.application.routes.draw do
  root :to => "graduates#index"

  resources :graduates
  mount Api::Root, at: "/"

  mount GrapeSwaggerRails::Engine => '/swagger'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graduate.rb
class Graduate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/graduates_controller.rb
class GraduatesController < ApplicationController
  before_action :set_graduate, only: [:show, :edit, :update, :destroy]

  # GET /graduates
  # GET /graduates.json
  def index
    @graduates = Graduate.all
  end

  # GET /graduates/1
  # GET /graduates/1.json
  def show
  end

  # GET /graduates/new
  def new
    @graduate = Graduate.new
  end

  # GET /graduates/1/edit
  def edit
  end

  # POST /graduates
  # POST /graduates.json
  def create
    @graduate = Graduate.new(graduate_params)

    respond_to do |format|
      if @graduate.save
        format.html { redirect_to @graduate, notice: 'Graduate was successfully created.' }
        format.json { render :show, status: :created, location: @graduate }
      else
        format.html { render :new }
        format.json { render json: @graduate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graduates/1
  # PATCH/PUT /graduates/1.json
  def update
    respond_to do |format|
      if @graduate.update(graduate_params)
        format.html { redirect_to @graduate, notice: 'Graduate was successfully updated.' }
        format.json { render :show, status: :ok, location: @graduate }
      else
        format.html { render :edit }
        format.json { render json: @graduate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graduates/1
  # DELETE /graduates/1.json
  def destroy
    @graduate.destroy
    respond_to do |format|
      format.html { redirect_to graduates_url, notice: 'Graduate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graduate
      @graduate = Graduate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def graduate_params
      params.require(:graduate).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graduates_helper.rb
module GraduatesHelper
end

app/views/graduates/_form.html.erb
<%= form_with(model: graduate, local: true) do |form| %>
  <% if graduate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(graduate.errors.count, "error") %> prohibited this graduate from being saved:</h2>

      <ul>
        <% graduate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/graduates/edit.html.erb
<h1>Editing Graduate</h1>

<%= render 'form', graduate: @graduate %>

<%= link_to 'Show', @graduate %> |
<%= link_to 'Back', graduates_path %>

app/views/graduates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Graduates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graduates.each do |graduate| %>
      <tr>
        <td><%= graduate.name %></td>
        <td><%= link_to 'Show', graduate %></td>
        <td><%= link_to 'Edit', edit_graduate_path(graduate) %></td>
        <td><%= link_to 'Destroy', graduate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graduate', new_graduate_path %>

app/views/graduates/new.html.erb
<h1>New Graduate</h1>

<%= render 'form', graduate: @graduate %>

<%= link_to 'Back', graduates_path %>

app/views/graduates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @graduate.name %>
</p>

<%= link_to 'Edit', edit_graduate_path(@graduate) %> |
<%= link_to 'Back', graduates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrapeApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>